### ISSUE TITLE
删除文件的操作无法同步远程

### ISSUE THREAD

**Issue by wan-maoyuan** [no-src/gofs#181]
先同步了一些文件到Minio服务器中，删除源文件夹中的文件，minio服务器中的文件还在

**Comment by mstmdev** [comment]
可以提供一下客户端的相关命令或配置么？

**Comment by wan-maoyuan** [comment]
客户端启动命令
```shell
gofs -source="/data1/minio-data" -dest="minio://127.0.0.1:9000/?secure=false&local_sync    _disabled=false&path=/data1/minio-data&remote_path=minio-data" -users=“12345678"  -sync_cron="2 * * * * *"
``` 

想minio 同步文件之后，删除source文件夹下的部分文件，minio里面的相应文件不会删除。

**Comment by mstmdev** [comment]
我在本地使用最新版的MinIO测试了一下，暂时没有复现这个问题，可以提供更多的环境信息么，比如操作系统、MinIO运行配置、以及golang版本等等信息。

另外我添加了一些MinIO相关的集成测试#182，测试已通过。你也可以在Github Actions测试下你的用例，看看是否能在上面复现你遇到的问题。@wan-maoyuan

**Comment by wan-maoyuan** [comment]
开始我用的bitnami/minio这个镜像有问题，现在我换成了minio/minio这个镜像可以了

**Comment by mstmdev** [comment]
我试了下`bitnami/minio`这个镜像，好像也可以。不过还是使用官方的镜像靠谱些。目前官方支持[DockerHub](https://hub.docker.com/r/minio/minio)与[Quay](https://quay.io/repository/minio/minio?tab=info)。

[Platform Support](https://min.io/docs/minio/container/operations/installation.html#platform-support)
