### ISSUE TITLE
重命名函数好像不大对劲

### ISSUE THREAD

**Issue by 88250** [no-src/gofs#19]
在阅读代码时发现的，不太确定是否是设计如此，

https://github.com/no-src/gofs/blob/56e6dda9c319de23cc55dd30ae23534a4e0ab2eb/server/handler/push_handler.go#L147

**Comment by mstmdev** [comment]
> 在阅读代码时发现的，不太确定是否是设计如此，
> 
> https://github.com/no-src/gofs/blob/56e6dda9c319de23cc55dd30ae23534a4e0ab2eb/server/handler/push_handler.go#L147

当前设计上如此，因为一个文件重命名操作会依次触发`RENAME`、`CREATE`、`WRITE`事件，而且目前`RENAME`事件只能拿到原始文件名，无法得知重命名后的文件名，所以实际上在处理重命名动作时会进行分解，即`RENAME=REMOVE+CREATE+WRITE`。
另外`os.Rename`在Windows下好像也无法处理跨分区的情况，所以还是需要进行动作分解。

**Comment by 88250** [comment]
明白了，感谢回复。
