### ISSUE TITLE
How to use gofs as a library

### ISSUE THREAD

**Issue by rizrmd** [no-src/gofs#22]
Hi.

Looks like gofs is a big project. How do I use this as a library for synchronizing directory in my local machine to ssh server ?

**Comment by mstmdev** [comment]
Currently support synchronizing directory in your local machine to the [gofs](https://github.com/no-src/gofs#remote-push-server) server, you can use the `gofs` as a library like the following code:

``` go
package main

import (
	"os"

	"github.com/no-src/gofs/cmd"
)

func main() {
	cmd.RunWithArgs([]string{
		os.Args[0],
		`-source=rs://127.0.0.1:8105`,
		`-dest=./dest`,
		`-users=gofs|password`,
	})
}

```

And more expose functions like `Run` and `RunWithConfig`.

More standard protocols like the SFTP will be supported in the future, if you don't want to deploy the `gofs` server side.

**Comment by rizrmd** [comment]
Great, thanks!
