### ISSUE TITLE
remote_client_sync模式当同步路径中包含#，数据不同步

### ISSUE THREAD

**Issue by lemon65535** [no-src/gofs#220]
当同步路径中包含#时，数据被截断，无法同步文件:
client 日志:
```
[2023-08-03 11:10:55] [INFO] start execute cron task, spec=[*/5 * * * * *]
[2023-08-03 11:10:55] [ERROR] sync remote file to local disk error => [syncPath=https://10.80.77.253/source/test1#2/test#1.txt?atime=1691031070&ctime=1691031065&dir=0&hash=00000000&mtime=1691030467&size=0]. file does not exist
[2023-08-03 11:10:55] [ERROR] sync remote file to local disk error => [syncPath=https://10.80.77.253/source/test1#2/123#test.txt?atime=1691031400&ctime=1691031400&dir=0&hash=00000000&mtime=1690971348&size=0]. file does not exist
```

server 日志:
```
[2023-08-03 11:11:30] [GIN] | 404 |     194.394µs |      10.80.76.7 | GET      "/source/test1"
[2023-08-03 11:11:30] [GIN] | 404 |     218.218µs |      10.80.76.7 | GET      "/source/test1"
```

server 目录:
```
[root@77253 /home/test/source]# ll *
-rw-r--r-- 1 root root 1720475571 Aug  2 14:51 nohup.out.tmp

test1#2:
total 0
-rw-r--r-- 1 root root 0 Aug  2 18:15 123#test.txt
-rw-r--r-- 1 root root 0 Aug  3 10:41 test#1.txt
[root@77253 /home/test/source]# ll
total 1680152
-rw-r--r-- 1 root root 1720475571 Aug  2 14:51 nohup.out.tmp
drwxr-xr-x 2 root root         44 Aug  3 10:56 test1#2
```

**Comment by mstmdev** [comment]
感谢反馈，文件路径中包含特殊字符会导致路径被截断，已修复，请拉取主分支最新代码重新编译试下

Fixed by #221

**Comment by lemon65535** [comment]
非常感谢，我刚已经拉取主分支重新测试了，问题已修复！

**Comment by lemon65535** [comment]
我这边测试还发现一个问题，当原目录下存在软链时:
1. 当软链指向的是一个不存在的地址时，目标不同步软链文件；
2. 当软链指向的是一个存在的文件时，目标目录下会将该软链指向的文件重新复制一遍；

这个有考虑修复一下吗？
![image](https://github.com/no-src/gofs/assets/13741739/fd68d84d-cde6-408e-bd9a-21179c25aa9f)

**Comment by mstmdev** [comment]
两种情况下，你期望的行为分别是什么呢？

**Comment by lemon65535** [comment]
1. 当软链指向的是一个不存在的地址时，创建一个软链文件，指向该不存在的文件地址
2. 当软链指向的是一个存在的文件时，目标目录下也对应创建一个软链文件，指向一个存在的文件(这样不需要再复制一遍源文件)

这样能够保证原始目录和目标目录的一致性，我这边用rsync做同步时也是这样的一个效果。

**Comment by mstmdev** [comment]
需要做一些测试来评估下，因为涉及到跨操作系统和存储目标非磁盘的情况，还有会对实时同步的逻辑造成影响。

第2种情况下重复复制确实是一个问题，需要一个解决方案来优化这个问题（覆盖全场景或者部分场景）。

**Comment by mstmdev** [comment]
嗯，针对这个具体的场景，你的思路是对的，细节上可能还会牵扯出更多的相关逻辑需要修改。

比如如果要支持软链接的下发与创建，就得考虑是否支持软链接的上传等等。同时也需要考虑是否会因为软链接导致source和dest目录之外的文件被恶意访问的问题，一些开放接口上就需要支持安全边界的检查和控制。

还有linux上的软链接同步到windows该如何处理。两者的软链接看起来好像并不兼容，而且windows上创建软链接貌似还需要管理员的权限，让软件的使用变得更加复杂。

另外除了这个场景之外，想要保持基本规则的统一，需要考虑与MinIO，SFTP等集成时如何处理软链接的问题。

**Comment by mstmdev** [comment]
可以先实验性的实现部分功能看看效果，以及评估对于现有代码会不会产生大的破坏。
目前来看，对于软链接，除了MinIO，其他场景理论上应该都是可以实现的。
对于MinIO，或许可以参考git对于软链接的实现，将其存储为一个特殊的文件来处理。


| Features                                                                | Create          | Remove             | Read             |
|-------------------------------------------------------------------------|--------------------|--------------------|--------------------|
| [Local Disk](https://github.com/no-src/gofs#local-disk)                 | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [Remote Disk Server](https://github.com/no-src/gofs#remote-disk-server) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [Remote Disk Client](https://github.com/no-src/gofs#remote-disk-client) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [Remote Push Server](https://github.com/no-src/gofs#remote-push-server) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [Remote Push Client](https://github.com/no-src/gofs#remote-push-client) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [SFTP Pull Client](https://github.com/no-src/gofs#sftp-pull-client)     | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [SFTP Push Client](https://github.com/no-src/gofs#sftp-push-client)     | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| [MinIO Pull Client](https://github.com/no-src/gofs#minio-pull-client)   | :x:                |:x:                |:x:                |
| [MinIO Push Client](https://github.com/no-src/gofs#minio-push-client)   |:x:                |:x:                |:x:                |
| [File Server](https://github.com/no-src/gofs#file-server)               | :white_check_mark: | :white_check_mark: | :white_check_mark: |

**Comment by mstmdev** [comment]
另外对于软链接无法低成本的实现文件的实时同步，只能通过手动全量同步或者定时同步来实现同步软链接指向的真实内容，即软链接不支持实时同步。

对于软链接指向的文件在source目录之内和source目录之外，具体处理逻辑可能也会不同，需要考虑是否允许同步链接到source目录之外的真实文件（在全量同步或定时同步的场景下）。

**Comment by lemon65535** [comment]
软连接不支持实时同步是因为什么原因呢？fsnotify能够识别出软连接文件的变更吗？
如果软连接指向的文件指向source之外，是否能通过参数让用户决定如何处理？

**Comment by mstmdev** [comment]
我试了下好像不能，我也查了下资料，软链接应该是只能触发Create与Remove这样的事件，应该是软链接的自身特性导致的，不是库的原因。

另外如果软链接指向了source目录下文件，并且假设软链接的文件内容变更也会触发相应事件，那此时可能会有两个协程同时对同一个文件进行更新（源文件和软链接触发了2个事件），也是存在一定矛盾的，软链接不支持实时同步反而可以规避这个问题。

第二个问题提供参数让用户参数控制也是可以的，但是会增加复杂度，需要验证和评估下。

**Comment by lemon65535** [comment]
针对第一点，照这个理解，确实不太适合做成实时同步。
定时同步以及手动全量同步能支持也可以理解，那照这样来看的话，干脆实时同步针对软链就不处理，软链的问题放在定时同步或全量同步中进行处理，能够更简单的实现功能。

**Comment by mstmdev** [comment]
赞同，以下是我理解，是否和你的想法一致？

在实时同步场景下,软链接只处理Create与Remove事件，如果dest支持软链接则创建软链接，如果不支持软链接（如MinIO），则创建一个自定义的特殊文件来记录软链接信息，例如[这个例子](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md)。


另外可以通过新增一个flag来支持同步软链接指向的真实文件，而不是链接本身，类似与rsync的`-L`参数，因为软链接可能指向source目录外的文件，存在需要同步原始文件的需求。

考虑到安全问题，还需要新增一个flag来控制指向source目录之外的软链接的行为。

**Comment by mstmdev** [comment]
实现同步软链接本身作为默认行为，已合并 #230

**Comment by lemon65535** [comment]
不好意思，最近几天比较忙。上上周我使用sersync2+rsync方式尝试同步目录的时候，就碰到了软链循环引用导致死循环的问题，这个确实需要考虑的。另外新feature是已经合并至master分支了吗？需要我本地拉下来build是吧。

**Comment by mstmdev** [comment]
目前主分支默认会同步软链接符号本身，并不会同步符号指向的内容。因为对于同步真实指向的文件还有一系列的问题没有解决，如你遇到的死循环问题等等。
目前在 #231 进行实验性的尝试，暂时不会合并

**Comment by mstmdev** [comment]
新增`-copy_link`和`-copy_unsafe_link`命令行参数支持在磁盘间进行同步时，控制是否同步软链接指向的真实文件。
为了保持代码的稳定性，目前这两个命令行参数只会[在本地磁盘间同步](https://github.com/no-src/gofs/blob/main/README-CN.md#%E5%9C%A8%E7%A3%81%E7%9B%98%E4%B9%8B%E9%97%B4%E5%90%8C%E6%AD%A5)时生效。

#231 已合并 @lemon65535
