### ISSUE TITLE
Is gofs send all files or only the difference ?

### ISSUE THREAD

**Issue by rizrmd** [no-src/gofs#23]
One question,

Suppose I have a large folder that frequently changes in my local machine, and some file are huge (1gb+).

Is gofs send whole files on each changes, or just the diff — like git ?

**Comment by mstmdev** [comment]
There are some optimizations for the big file in the universal scene.

The gofs will generate some checkpoints to calculate the file chunk hash value when the file is modified. You can change
the `-checkpoint_count` and `-chunk_size` flags to control the checkpoints, and for more information see also the [checksum](https://github.com/no-src/gofs#checksum) section.

For example, execute the following command to output the file checkpoints with default setting:

```bash
$ gofs -source=go1.18.3.linux-amd64.tar.gz -checksum
```

Output:

```json
[
    {
        "offset": 1048576,
        "hash": "a9168dd0ef9e6cdfccb3b71de077ec73"
    },
    {
        "offset": 13631488,
        "hash": "f59a9759d0dfe1a149568cb40ad4af4d"
    },
    {
        "offset": 27262976,
        "hash": "79711c44daf0a2e5479c108db7568872"
    },
    {
        "offset": 40894464,
        "hash": "9c89d776454ec8f03ba916e10e158455"
    },
    {
        "offset": 54525952,
        "hash": "36ace0da4eae494ab6a404c2879098a6"
    },
    {
        "offset": 68157440,
        "hash": "8d2fc7bb6e4b409f54e0a116f3690ea9"
    },
    {
        "offset": 81788928,
        "hash": "96f11fa855f368a56f170cab6f7b0a89"
    },
    {
        "offset": 95420416,
        "hash": "11127168e9364025a1ae0524a0154d2b"
    },
    {
        "offset": 109051904,
        "hash": "e215df2b5fe8e34ec3ad8f354db62039"
    },
    {
        "offset": 122683392,
        "hash": "918aea633289b221faea259c2a50c5f1"
    },
    {
        "offset": 136314880,
        "hash": "147792aea5544021114fd3d44478c3f0"
    },
    {
        "offset": 141748419,
        "hash": "0dec4243438f5c1c40706d5c6d843ac7"
    }
]
```


The gofs will compare the local source file checkpoints with the destination file checkpoints and sync the data chunks after the last checkpoint offset is hit.
