### ISSUE TITLE
是否可以直接打包一个可执行文件

### ISSUE THREAD

**Issue by xdkaka** [no-src/gofs#34]
都用go了，生产环境就没必要安装go环境了吧
是否可以直接打包一个可执行文件，直接在生产环境上运行呢
经过测试，通过下面方式打包，没有打包出可执行文件，还请指教
````
cd cmd/gofs/
env GOOS=linux GOARCH=386 go build main.go
````

**Comment by mstmdev** [comment]
已修复，linux 386环境下，类型不匹配导致编译错误

Fixed by #35
