### ISSUE TITLE
delete the source files and source directories 

### ISSUE THREAD

**Issue by xiongdashan** [no-src/gofs#350]
Hi everyone,

I would like to delete the source files and source directories after the file synchronization is complete. I couldn't find any related settings in the documentation. Is there a good way to achieve this?

tks!!

**Comment by mstmdev** [comment]
This feature is not currently supported. It seems to be a dangerous operation. 
Maybe you can use a custom shell script to achieve similar functionality (**must use the latest code from the main branch**), 
such as deleting the source directory after completing a full synchronization.

```
./gofs -source=./source -dest=./dest -sync_once  && rm -rf ./source
```

To reiterate, this is a **dangerous** operation and has not been fully tested.

**Comment by xiongdashan** [comment]
Copy than, thank you for your reponse!
