### ISSUE TITLE
Customise the file server port

### ISSUE THREAD

**Issue by qsk5yrs** [no-src/gofs#368]
Customise the file server port, for example, port 18080, when the client specifies the port to access, it still accesses the default port 443, and prompts a connection timeout when synchronising files.

**Comment by mstmdev** [comment]
You can use the `-server_addr` flag to specify the startup port of the file server, and then pass it to the client via the `fs_server` parameter.
The `fs_server` might be a proxy address of nginx, and the client cannot manually specify the port for the HTTP file server. 

Here's an example:
```
# server
gofs -source="rs://127.0.0.1:8105?mode=server&local_sync_disabled=true&path=./source&fs_server={https://file.demo.com or https://127.0.0.1:18080}" -server_addr=:18080 -dest=./dest -users="gofs|password|rw" -tls_cert_file=cert.pem -tls_key_file=key.pem -push_server -token_secret=mysecret_16bytes

# client
gofs -source="./source" -dest="rs://127.0.0.1:8105?local_sync_disabled=false&path=./dest" -users="gofs|password" -tls_cert_file=cert.pem

```

**Comment by qsk5yrs** [comment]
> You can use the `-server_addr` flag to specify the startup port of the file server, and then pass it to the client via the `fs_server` parameter. The `fs_server` might be a proxy address of nginx, and the client cannot manually specify the port for the HTTP file server.
> 
> Here's an example:
> 
> ```
> # server
> gofs -source="rs://127.0.0.1:8105?mode=server&local_sync_disabled=true&path=./source&fs_server={https://file.demo.com or https://127.0.0.1:18080}" -server_addr=:18080 -dest=./dest -users="gofs|password|rw" -tls_cert_file=cert.pem -tls_key_file=key.pem -push_server -token_secret=mysecret_16bytes
> 
> # client
> gofs -source="./source" -dest="rs://127.0.0.1:8105?local_sync_disabled=false&path=./dest" -users="gofs|password" -tls_cert_file=cert.pem
> ```

Thanks,it works.
