### ISSUE TITLE
Storage of s3 protocol

### ISSUE THREAD

**Issue by qsk5yrs** [no-src/gofs#374]
Does the minio client work with all s3 protocol storage like aliyun oss. i can only use aliyun oss in this intranet environment.

**Comment by mstmdev** [comment]
I'm not entirely sure about this, as I haven't used OSS service before. I see that the official website provides a dedicated [Go driver](https://github.com/aliyun/aliyun-oss-go-sdk). 
We might need to purchase the related service to test it out.

**Comment by qsk5yrs** [comment]
Okay, I get it. Thanks.
